package routing

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func TestGenerateEmpty(t *testing.T) {
	path := filepath.Join(t.TempDir(), "dynamic.yaml")
	g := NewTraefikGenerator(path)

	if err := g.Generate(nil); err != nil {
		t.Fatalf("Generate: %v", err)
	}

	data, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("reading output: %v", err)
	}

	content := string(data)
	if !strings.Contains(content, "Auto-generated by aurelia") {
		t.Error("expected header comment")
	}
}

func TestGenerateSingleHTTPService(t *testing.T) {
	path := filepath.Join(t.TempDir(), "dynamic.yaml")
	g := NewTraefikGenerator(path)

	routes := []ServiceRoute{
		{Name: "grafana", Hostname: "grafana.studio.internal", Port: 3000, TLS: false},
	}

	if err := g.Generate(routes); err != nil {
		t.Fatalf("Generate: %v", err)
	}

	data, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("reading output: %v", err)
	}

	content := string(data)
	if !strings.Contains(content, "Host(`grafana.studio.internal`)") {
		t.Error("expected hostname rule")
	}
	if !strings.Contains(content, "http://127.0.0.1:3000") {
		t.Error("expected backend URL")
	}
	if !strings.Contains(content, "web") {
		t.Error("expected web entrypoint for non-TLS")
	}
	if strings.Contains(content, "websecure") {
		t.Error("should not have websecure for non-TLS service")
	}
}

func TestGenerateTLSService(t *testing.T) {
	path := filepath.Join(t.TempDir(), "dynamic.yaml")
	g := NewTraefikGenerator(path)

	routes := []ServiceRoute{
		{Name: "chat", Hostname: "chat.studio.internal", Port: 8090, TLS: true},
	}

	if err := g.Generate(routes); err != nil {
		t.Fatalf("Generate: %v", err)
	}

	data, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("reading output: %v", err)
	}

	content := string(data)
	if !strings.Contains(content, "websecure") {
		t.Error("expected websecure entrypoint for TLS service")
	}
	if !strings.Contains(content, "Host(`chat.studio.internal`)") {
		t.Error("expected hostname rule")
	}
	if !strings.Contains(content, "tls:") {
		t.Error("expected tls block")
	}
}

func TestGenerateMTLSService(t *testing.T) {
	path := filepath.Join(t.TempDir(), "dynamic.yaml")
	g := NewTraefikGenerator(path)

	routes := []ServiceRoute{
		{Name: "signal-api", Hostname: "signal-api.studio.internal", Port: 8093, TLS: true, TLSOptions: "mtls"},
	}

	if err := g.Generate(routes); err != nil {
		t.Fatalf("Generate: %v", err)
	}

	data, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("reading output: %v", err)
	}

	content := string(data)
	if !strings.Contains(content, "mtls@file") {
		t.Error("expected mtls@file TLS options reference")
	}
}

func TestGenerateMultipleServices(t *testing.T) {
	path := filepath.Join(t.TempDir(), "dynamic.yaml")
	g := NewTraefikGenerator(path)

	routes := []ServiceRoute{
		{Name: "chat", Hostname: "chat.studio.internal", Port: 8090, TLS: true},
		{Name: "auth", Hostname: "auth.studio.internal", Port: 8092, TLS: true},
		{Name: "grafana", Hostname: "grafana.studio.internal", Port: 3000, TLS: false},
		{Name: "signal-api", Hostname: "signal-api.studio.internal", Port: 8093, TLS: true, TLSOptions: "mtls"},
	}

	if err := g.Generate(routes); err != nil {
		t.Fatalf("Generate: %v", err)
	}

	data, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("reading output: %v", err)
	}

	content := string(data)
	for _, r := range routes {
		if !strings.Contains(content, r.Hostname) {
			t.Errorf("expected %s in output", r.Hostname)
		}
	}
}

func TestGenerateCreatesParentDir(t *testing.T) {
	dir := t.TempDir()
	path := filepath.Join(dir, "nested", "dir", "dynamic.yaml")
	g := NewTraefikGenerator(path)

	if err := g.Generate([]ServiceRoute{
		{Name: "test", Hostname: "test.local", Port: 8080},
	}); err != nil {
		t.Fatalf("Generate: %v", err)
	}

	if _, err := os.Stat(path); err != nil {
		t.Errorf("expected file to exist: %v", err)
	}
}

func TestGenerateOverwritesPrevious(t *testing.T) {
	path := filepath.Join(t.TempDir(), "dynamic.yaml")
	g := NewTraefikGenerator(path)

	// First generation with two services
	g.Generate([]ServiceRoute{
		{Name: "chat", Hostname: "chat.studio.internal", Port: 8090, TLS: true},
		{Name: "auth", Hostname: "auth.studio.internal", Port: 8092, TLS: true},
	})

	// Second generation with only one — auth is gone
	g.Generate([]ServiceRoute{
		{Name: "chat", Hostname: "chat.studio.internal", Port: 8090, TLS: true},
	})

	data, _ := os.ReadFile(path)
	content := string(data)

	if !strings.Contains(content, "chat.studio.internal") {
		t.Error("expected chat in output")
	}
	if strings.Contains(content, "auth.studio.internal") {
		t.Error("auth should have been removed on regeneration")
	}
}

func TestSanitizeName(t *testing.T) {
	if sanitizeName("my_service") != "my-service" {
		t.Errorf("expected underscores replaced with hyphens")
	}
	if sanitizeName("chat") != "chat" {
		t.Errorf("simple name should pass through")
	}
}
